version: '2'
services:
  app:
    container_name: app
    build: .
    ports:
      - "9000:8080"
    environment:
      - USE_RDS=true
      - RDS_USERNAME=root
      - RDS_PASSWORD=root
      - RDS_HOSTNAME=app_db
      - RDS_PORT=3306
      - RDS_DB_NAME=app
      - APP_NAME=newapp
    depends_on:
      - "mysql"
  mysql:
    container_name: app_db
    ports:
      - "33060:3306"
    image: "mysql:5.6.36"
    volumes:
       - ./docker/app.cnf:/etc/mysql/conf.d/app.cnf    
    environment:
      - MYSQL_ROOT_PASSWORD=root
