"""add ip column to server remove from users

Revision ID: 2_1505641323.0060596
Revises: 1_1505641273.4730737
Create Date: 2017-09-17 12:42:03.533277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2_1505641323.0060596'
down_revision = '1_1505641273.4730737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('ip', mysql.VARCHAR(length=18), nullable=True))
    op.drop_column('users', 'ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ip', mysql.VARCHAR(length=18), nullable=True))
    op.drop_column('servers', 'ip')
    # ### end Alembic commands ###
